language: node_js
node_js:
  - "7"
  - "8"
addons:
  code_climate:
    repo_token: dd12de3cad4172ec4ef4934f89995c6963264f4ce8a67faca4f9e7a7b5141ca9
after_success:
  - npm install -g codeclimate-test-reporter
  - codeclimate-test-reporter < coverage/lcov.info